timeout: use CLOCK_MONOTONIC if CLOCK_BOOTTIME is missing
DragonFly, FreeBSD < 13.1, NetBSD, OpenBSD < 6.3 lack CLOCK_BOOTTIME.

src/gm-timeout.c:109:31: error: use of undeclared identifier 'CLOCK_BOOTTIME'
  timer->fd = timerfd_create (CLOCK_BOOTTIME, 0);
                              ^

https://github.com/openbsd/src/commit/b50bd52298d2
https://github.com/freebsd/freebsd-src/commit/5918f4865267

Part-of: <https://gitlab.gnome.org/World/Phosh/gmobile/-/merge_requests/11>