build: depend on epoll-shim for timerfd_* on non-Linux
DragonFly, FreeBSD < 14.0, NetBSD < 10.0, OpenBSD lack native timerfd.

src/gm-timeout.c:13:10: fatal error: 'sys/timerfd.h' file not found
 #include <sys/timerfd.h>
          ^~~~~~~~~~~~~~~

https://github.com/netbsd/src/commit/75f1bc6655cf
https://github.com/freebsd/freebsd-src/commit/af93fea71038

Part-of: <https://gitlab.gnome.org/World/Phosh/gmobile/-/merge_requests/11>